=== Tigeroff2002/Labs_Maga/CrossPlatformSystems/Diagrams/dtd_description.dtd
<!DOCTYPE data [
    <!ENTITY % user_attrs "id ID, email CDATA, role CDATA, full_name CDATA">
    <!ENTITY % city_attrs "id ID, name CDATA, crossroad_numbers CDATA">
    <!ENTITY % roadsegment_attrs "id ID, city_id IDREF, start_coord CDATA, end_coord CDATA, length CDATA, quality_factor CDATA, user_intensity CDATA">
    <!ENTITY % crossroad_attrs "id ID, city_id IDREF, coord CDATA, type CDATA">
    <!ENTITY % crossroadlink_attrs "crossroad_id IDREF, road_segment_id IDREF, road_degree CDATA">
    <!ENTITY % roaditem_attrs "id ID, item_type CDATA, coord CDATA, weight CDATA, actuality CDATA">
    <!ENTITY % roaditemlink_attrs "road_item_id IDREF, road_segment_id IDREF, factor_number CDATA">
    <!ENTITY % request_attrs "id ID, user_id IDREF, start_point CDATA, end_point CDATA, datetime CDATA, preference_parameter CDATA">
    <!ENTITY % route_attrs "id ID, request_id IDREF, total_distance CDATA, time CDATA, total_weight CDATA">
    <!ENTITY % video_attrs "id ID, user_id IDREF, cloud_link CDATA, timelapses_json CDATA">
    <!ENTITY % imagetimeframe_attrs "id ID, video_id IDREF, cloud_link CDATA, coord CDATA, reliability_factor CDATA">
    <!ENTITY % routeroadsegmentlink_attrs "route_id IDREF, road_segment_id IDREF, sequence_number CDATA, start_coord CDATA, end_coord CDATA, total_distance CDATA, total_time CDATA">

    <!ELEMENT data (user*, city*, roadsegment*, crossroad*, crossroadlink*, roaditem*, roaditemlink*, request*, route*, video*, imagetimeframe*, routeroadsegmentlink*)>

    <!ELEMENT user EMPTY>
    <!ATTLIST user %user_attrs;>

    <!ELEMENT city EMPTY>
    <!ATTLIST city %city_attrs;>

    <!ELEMENT roadsegment EMPTY>
    <!ATTLIST roadsegment %roadsegment_attrs;>

    <!ELEMENT crossroad EMPTY>
    <!ATTLIST crossroad %crossroad_attrs;>

    <!ELEMENT crossroadlink EMPTY>
    <!ATTLIST crossroadlink %crossroadlink_attrs;>

    <!ELEMENT roaditem EMPTY>
    <!ATTLIST roaditem %roaditem_attrs;>

    <!ELEMENT roaditemlink EMPTY>
    <!ATTLIST roaditemlink %roaditemlink_attrs;>

    <!ELEMENT request EMPTY>
    <!ATTLIST request %request_attrs;>

    <!ELEMENT route EMPTY>
    <!ATTLIST route %route_attrs;>

    <!ELEMENT video EMPTY>
    <!ATTLIST video %video_attrs;>

    <!ELEMENT imagetimeframe EMPTY>
    <!ATTLIST imagetimeframe %imagetimeframe_attrs;>

    <!ELEMENT routeroadsegmentlink EMPTY>
    <!ATTLIST routeroadsegmentlink %routeroadsegmentlink_attrs;>
]>

=== Tigeroff2002/Labs_Maga/CrossPlatformSystems/Diagrams/dtd_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "dtd_description.dtd">
<data>
    <user id="1" email="user1@example.com" role="admin" full_name="John Doe"/>
    <user id="2" email="user2@example.com" role="user" full_name="Jane Smith"/>
    
    <city id="1" name="City1" crossroad_numbers="10"/>
    
    <roadsegment id="1" city_id="1" start_coord="40.7128, -74.0060" end_coord="40.7138, -74.0050" length="1500.5" quality_factor="0.8" user_intensity="0.75"/>
    
    <crossroad id="1" city_id="1" coord="40.7128, -74.0060" type="traffic_light"/>
    <crossroad id="2" city_id="1" coord="40.7138, -74.0050" type="roundabout"/>
    
    <crossroadlink crossroad_id="1" road_segment_id="1" road_degree="2"/>
    <crossroadlink crossroad_id="2" road_segment_id="1" road_degree="1"/>
    
    <roaditem id="1" item_type="sign" coord="40.7128, -74.0060" weight="10" actuality="true"/>
    <roaditem id="2" item_type="lamp" coord="40.7138, -74.0050" weight="5" actuality="false"/>
    
    <roaditemlink road_item_id="1" road_segment_id="1" factor_number="1.5"/>
    <roaditemlink road_item_id="2" road_segment_id="1" factor_number="1.0"/>
    
    <request id="1" user_id="1" start_point="40.7128, -74.0060" end_point="40.7138, -74.0050" datetime="2025-03-09T12:00:00" preference_parameter="fastest"/>
    
    <route id="1" request_id="1" total_distance="2.0" time="5.0" total_weight="15.0"/>
    
    <video id="1" user_id="1" cloud_link="http://cloudlink/video1" timelapses_json="{}"/>
    <video id="2" user_id="2" cloud_link="http://cloudlink/video2" timelapses_json="{}"/>
    
    <imagetimeframe id="1" video_id="1" cloud_link="http://cloudlink/image1" coord="40.7128, -74.0060" reliability_factor="0.9"/>
    <imagetimeframe id="2" video_id="2" cloud_link="http://cloudlink/image2" coord="40.7138, -74.0050" reliability_factor="0.8"/>
    
    <routeroadsegmentlink route_id="1" road_segment_id="1" sequence_number="1" start_coord="40.7128, -74.0060" end_coord="40.7138, -74.0050" total_distance="2.0" total_time="5.0"/>
</data>
